<a href="https://colab.research.google.com/github/ChristianVaughn/BioInspiredML/blob/main/Eight_Queens/8queens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

numberOfQueens = 8
maxPopSize = 100
maxIterations = 10000
mutationProbability = 0.8

In [2]:
class Queens:
    def __init__ (self, genotype, fitness):
        self.genotype = genotype
        self.fitness = fitness
    def updateFitness(self, fitness):
        self.fitness = fitness
    def updateGenotype(self, genotype):
        self.genotype = genotype
    def getFitness(self):
        return self.fitness
    def getGenotype(self):
        return self.genotype
    

In [3]:
def get_fitness(genotype):
  checks = 0
  #check for row and column checks by seeing how many unique numbers are in the list. if no checks there should be 8 unique numbers, so 0 checks.
  up_down_checks = len(genotype) - len(np.unique(genotype)) 

  #check for diagonals
  for i in range(len(genotype)):
    for j in range(len(genotype)):
      x = abs(i-j)
      y = abs(genotype[i] - genotype[j])
      if (i != j and x == y):
        checks += 1
  checks += up_down_checks
  return 28 - checks

In [4]:
def init_population(populationSize,numberOfQueens):
  populationList = list()
  for offspring in range(populationSize):
    genotype = np.arange(numberOfQueens)
    np.random.shuffle(genotype)
    fitness = get_fitness(genotype)
    populationList.append(Queens(genotype, fitness))
  return populationList

In [5]:
def mutation(offspring):
  global mutationProbability

  randNum = random.random()
  if (randNum <= 0.8):
    i1, i2 = random.sample(range(len(offspring.genotype)), 2)
    genotype = offspring.genotype
    genotype[i1], genotype[i2] = genotype[i2], genotype[i1]
    offspring.updateGenotype(genotype)
    return offspring
  return offspring

In [6]:
def recombination(parentA, parentB):
  cutPoint = np.random.randint(len(parentA))
  genotype1 = np.append(parentA[0:cutPoint],parentB[cutPoint:])
  genotype2 = np.append(parentB[0:cutPoint],parentA[cutPoint:])
  return (Queens(genotype1, get_fitness(genotype1)), Queens(genotype2, get_fitness(genotype2)))

In [7]:
def selection():
  global population
  parents = np.random.choice(population, size=5)
  parents = parents.tolist()
  parents.sort(key=lambda x: x.fitness, reverse=True)
  offspring = recombination(parents[0].genotype,parents[1].genotype)

  offspring1 = mutation(offspring[0])
  offspring2 = mutation(offspring[1])

  #Replace 2 of population with the new children
  population.sort(key=lambda x: x.fitness, reverse=True)

  #for index,member in population:  #PYTHON NOT LETTING ME ITERATE OVER MY CLASS, AND I FORGOT HOW
  for index in range(len(population)):
    if (population[index].fitness < offspring1.fitness):
      population[index] = offspring1
      return
  #for index,member in population: #PYTHON NOT LETTING ME ITERATE OVER MY CLASS, AND I FORGOT HOW
  for index in range(len(population)):
    if (population[index].fitness < offspring2.fitness):
      population[index] = offspring2
      return

In [8]:
population = init_population(maxPopSize,numberOfQueens)

for iteration in range(maxIterations):
  selection()

print(len(population))

100


In [17]:
for index in range(len(population)):
  print(population[index].genotype)

[4 0 7 5 2 6 1 3]
[0 4 7 5 2 6 1 3]
[4 0 7 3 2 6 1 5]
[4 0 7 5 2 6 1 3]
[4 0 7 5 2 6 1 3]
[0 4 7 5 2 6 1 3]
[4 0 7 3 5 6 2 1]
[6 0 7 5 2 4 1 3]
[1 4 7 5 2 6 0 3]
[4 0 5 7 2 6 1 3]
[4 0 7 3 2 6 1 5]
[4 0 7 5 2 6 3 1]
[1 0 7 5 2 6 4 3]
[4 0 7 5 2 6 1 3]
[0 4 6 5 2 7 1 3]
[4 0 7 5 2 3 1 6]
[6 0 7 5 2 4 1 3]
[1 0 7 5 2 6 4 3]
[4 0 2 5 7 6 1 3]
[5 0 7 4 2 6 1 3]
[5 0 7 4 2 6 1 3]
[4 0 7 5 3 6 1 2]
[0 4 7 1 2 6 5 3]
[4 6 7 5 2 0 1 3]
[4 0 7 5 2 6 1 3]
[4 0 3 5 2 6 1 7]
[0 3 7 5 2 6 1 4]
[0 4 7 5 2 6 1 3]
[0 4 6 5 2 7 1 3]
[3 0 7 5 2 6 1 4]
[5 0 7 4 2 6 1 3]
[4 0 7 5 2 1 6 3]
[4 7 0 5 2 6 1 3]
[4 0 7 5 2 6 1 3]
[6 0 7 5 2 4 1 3]
[0 6 7 5 2 4 1 3]
[1 4 7 5 2 6 0 3]
[5 0 7 4 2 6 1 3]
[4 0 7 5 2 6 1 3]
[4 0 7 5 2 6 1 3]
[4 0 7 5 2 1 6 3]
[4 0 2 5 7 6 1 3]
[2 4 7 5 0 6 1 3]
[7 0 4 5 2 6 1 3]
[4 0 7 5 2 6 1 3]
[4 1 7 5 2 6 0 3]
[4 0 1 5 2 6 7 3]
[4 0 7 5 2 6 1 3]
[0 6 7 5 2 4 1 3]
[6 0 7 5 2 4 1 3]
[4 0 1 5 2 6 7 3]
[4 0 7 5 2 6 1 3]
[4 0 7 5 2 6 1 3]
[4 2 7 5 0 6 1 3]
[4 0 7 5 2 6 1 3]
[4 0 7 5 2